services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    expose:
      - "9000"  # only accessible to Nginx

  web:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"  # host port 80 → Nginx
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - n8n
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: blueflow
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: 256ddyu66@190
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    networks:
      - app-network
    expose:
      - "5678"
    environment:
      - N8N_HOST=n8n.blueflowautomation.com
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.blueflowautomation.com/
      - N8N_EDITOR_BASE_URL=https://n8n.blueflowautomation.com
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  mysql_data:
  n8n_data:

networks:
  app-network:
    driver: bridge